#当前启用的配置环境
spring:
  profiles:
    active: dev1
---
spring:
  application:
    name: eureka-peer
  config:
    activate:
      on-profile: dev

server:
  port: 9001

eureka:
  instance:
    hostname: dev
    instance-id: dev
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 100000
---
spring:
  application:
    name: eureka-peer1
  config:
    activate:
      on-profile: dev1

server:
  port: 9002

eureka:
  instance:
    hostname: dev1
    instance-id: dev1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 100000


---
spring:
  application:
    name: eureka-peer2
  config:
    activate:
      on-profile: dev2

server:
  port: 9003

eureka:
  instance:
    hostname: dev2
    instance-id: dev2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/,http://localhost:9003/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 100000
#是否拉取服务
#eureka.client.fetch-registry=false
#是否需要将自己注册进Eureka
#eureka.client.register-with-eureka=false
#Eureka注册中心客户端默认的地址 Zone指一个区域
#eureka.client.service-url.defaultZone=http://localhost:8001/eureka
#eureka.client.availability-zones.beijing:zone1
#eureka.client.service-url.zone1 = http://localhost:10001/eureka

#服务端等待时长,服务间同步数据等待时长
#eureka.server.wait-time-in-ms-when-sync-empty=0
#自我保护机制
#eureka.server.enable-self-preservation=true
#修改eureka nods节点数执行间隔
#eureka.server.peer-eureka-nodes-update-interval-ms=100000

#日志记录 查看Eureka是怎么保存注册者的信息
#logging.level.org.springframework.cloud=debug
#logging.level.com.netflix=debug



